
CREATE TABLE IF NOT EXISTS USER ( username TEXT PRIMARY KEY NOT NULL, password TEXT NOT NULL );
CREATE TABLE IF NOT EXISTS MEALPLAN ( username TEXT NOT NULL, day DATE NOT NULL, weekday TEXT NOT NULL, mealNum INT NOT NULL, name TEXT NOT NULL, PRIMARY KEY (username, day, mealNum));

DELETE FROM USER;
DELETE FROM MEALPLAN;

INSERT INTO USER VALUES ('subu', '1234');
INSERT INTO MEALPLAN VALUES ( 'subu', '2024-04-11', 'Friday', 1, "eggs" );
INSERT INTO MEALPLAN VALUES ( 'subu', '2024-04-12', 'Friday', 1, "friday" );
